basePath: /
definitions:
  interfaces.LoginInput:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  interfaces.RegisterInput:
    properties:
      email:
        type: string
      fullName:
        type: string
      password:
        type: string
      username:
        type: string
    type: object
  interfaces.TokenPair:
    properties:
      accessToken:
        type: string
      refreshToken:
        type: string
    type: object
  model.Role:
    properties:
      createdAt:
        type: string
      description:
        type: string
      id:
        type: string
      isActive:
        type: boolean
      isSystem:
        type: boolean
      name:
        type: string
      permissionKeys:
        description: 'ví dụ: ["employee.read","employee.write"]'
        items:
          type: string
        type: array
      updatedAt:
        type: string
    type: object
info:
  contact: {}
  description: |-
    API documentation for Management System
    # Error codes
    ### <span style="font-size:18px">- <code>120001</code>: Wrong pagination query</span>
    ### <span style="font-size:18px">- <code>120002</code>: Wrong query</span>
    ### <span style="font-size:18px">- <code>120003</code>: Wrong body</span>
    ### <span style="font-size:18px">- <code>121101</code>: Email template not found</span>
    ### <span style="font-size:18px">- <code>121204</code>: Invalid order</span>
    ### <span style="font-size:18px">- <code>121205</code>: Email template ID is missing</span>
    ### <span style="font-size:18px">- <code>121206</code>: Invalid email template ID</span>
    ### <span style="font-size:18px">- <code>121207</code>: Email template not found</span>
    ### <span style="font-size:18px">- <code>121208</code>: Stage not found</span>
    ### <span style="font-size:18px">- <code>121301</code>: Reject reason not found</span>
    ### <span style="font-size:18px">- <code>121401</code>: Question set not found</span>
    ### <span style="font-size:18px">- <code>121501</code>: Hiring team not found</span>
    ### <span style="font-size:18px">- <code>121502</code>: User not found</span>
    ### <span style="font-size:18px">- <code>122101</code>: Position not found</span>
    ### <span style="font-size:18px">- <code>122201</code>: Required field</span>
    ### <span style="font-size:18px">- <code>122202</code>: Stage not found</span>
    ### <span style="font-size:18px">- <code>122203</code>: Black list or duplicate</span>
    ### <span style="font-size:18px">- <code>122204</code>: Pool not found</span>
    ### <span style="font-size:18px">- <code>122205</code>: Candidate not found</span>
    ### <span style="font-size:18px">- <code>122301</code>: Label not found</span>
  title: Management System API
  version: "1.0"
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      parameters:
      - description: Credentials
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/interfaces.LoginInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/interfaces.TokenPair'
      summary: Login
      tags:
      - auth
  /auth/logout:
    post:
      parameters:
      - description: Refresh token
        in: query
        name: refreshToken
        required: true
        type: string
      responses:
        "204":
          description: No Content
          schema:
            type: string
      summary: Logout
      tags:
      - auth
  /auth/refresh:
    post:
      consumes:
      - application/json
      parameters:
      - description: Refresh token
        in: query
        name: refreshToken
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/interfaces.TokenPair'
      summary: Refresh token
      tags:
      - auth
  /auth/register:
    post:
      consumes:
      - application/json
      parameters:
      - description: Register
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/interfaces.RegisterInput'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            type: string
      summary: Register
      tags:
      - auth
  /roles:
    get:
      description: Lấy danh sách roles với phân trang và filter
      parameters:
      - description: Filter by role name
        in: query
        name: name
        type: string
      - description: Filter by status
        enum:
        - active
        - inactive
        in: query
        name: status
        type: string
      - default: 1
        description: Trang hiện tại (bắt đầu từ 1)
        in: query
        name: page
        type: integer
      - default: 20
        description: Số bản ghi mỗi trang
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: '{ items: Role[], meta: { count,current_page,per_page,total,total_pages
            } }'
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: List roles
      tags:
      - roles
    post:
      consumes:
      - application/json
      description: Tạo role mới
      parameters:
      - description: Role payload
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/model.Role'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/model.Role'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Create role
      tags:
      - roles
  /roles/{id}:
    delete:
      description: Xóa role theo ID
      parameters:
      - description: Role ID
        in: path
        name: id
        required: true
        type: string
      responses:
        "204":
          description: No Content
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Delete role
      tags:
      - roles
    get:
      description: Lấy thông tin role theo ID
      parameters:
      - description: Role ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Role'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get role by ID
      tags:
      - roles
    put:
      consumes:
      - application/json
      description: Cập nhật thông tin role
      parameters:
      - description: Role ID
        in: path
        name: id
        required: true
        type: string
      - description: Role payload
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/model.Role'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Role'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Update role
      tags:
      - roles
swagger: "2.0"
