basePath: /
definitions:
  model.Role:
    properties:
      createdAt:
        type: string
      description:
        type: string
      id:
        type: string
      isActive:
        type: boolean
      isSystem:
        type: boolean
      name:
        type: string
      permissionKeys:
        description: 'ví dụ: ["employee.read","employee.write"]'
        items:
          type: string
        type: array
      updatedAt:
        type: string
    type: object
info:
  contact: {}
  description: API documentation for Management System
  title: Management System API
  version: "1.0"
paths:
  /roles:
    get:
      description: Lấy danh sách roles với phân trang và filter
      parameters:
      - description: Filter by role name
        in: query
        name: name
        type: string
      - description: Filter by status
        enum:
        - active
        - inactive
        in: query
        name: status
        type: string
      - default: 1
        description: Trang hiện tại (bắt đầu từ 1)
        in: query
        name: page
        type: integer
      - default: 20
        description: Số bản ghi mỗi trang
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: '{ items: Role[], meta: { count,current_page,per_page,total,total_pages
            } }'
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: List roles
      tags:
      - roles
    post:
      consumes:
      - application/json
      description: Tạo role mới
      parameters:
      - description: Role payload
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/model.Role'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/model.Role'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Create role
      tags:
      - roles
  /roles/{id}:
    delete:
      description: Xóa role theo ID
      parameters:
      - description: Role ID
        in: path
        name: id
        required: true
        type: string
      responses:
        "204":
          description: No Content
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Delete role
      tags:
      - roles
    get:
      description: Lấy thông tin role theo ID
      parameters:
      - description: Role ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Role'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get role by ID
      tags:
      - roles
    put:
      consumes:
      - application/json
      description: Cập nhật thông tin role
      parameters:
      - description: Role ID
        in: path
        name: id
        required: true
        type: string
      - description: Role payload
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/model.Role'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Role'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Update role
      tags:
      - roles
swagger: "2.0"
